/*                                                 *\
** ----------------------------------------------- **
**             Calliope - Site Generator   	       **
** ----------------------------------------------- **
**  Copyright (c) 2020-2021 - Kyle Derby MacInnis  **
**                                                 **
**    Any unauthorized distribution or transfer    **
**       of this work is strictly prohibited.      **
**                                                 **
**               All Rights Reserved.              **
** ----------------------------------------------- **
\*                                                 */

import { Vector, set, lerp } from "../../engine/utils/math/vector.jsx";
import { ActionLoader } from "../utils/loaders.jsx";
import { Direction } from "../../engine/utils/enums.jsx";

export default {
  init: function (from, to, length) {
    console.log("loading - patrol");

    this.from = new Vector(...from);
    this.to = new Vector(...to);
    this.completed = false;
    this.lastKey = new Date().getTime();

    // TODO -- Implement A-star Pathfinding -
    // --> build move list based on passed in points

    // For now - mock
    this.moveList = [
      [from, to, length],
      [to, from, length],
    ]; // holds moves generated by A*

    this.moveIndex = 0; // holds index position
    this.length = length; // length of time per move
  },
  tick: function (time) {
    if (!this.loaded) return;
    this.checkInput(time);
    // load up moves - todo (improve this and make it less manual)
    let endTime = this.startTime + this.length;
    if (time > endTime + 2 * this.length) {
      let move = this.moveList[this.moveIndex];
      let facing = Direction.fromOffset([Math.round(move[1][0] - move[0][0]), Math.round(move[1][1] - move[0][1])]);
      // 10 seconds of patrolling
      // Check for zone change
      if (!this.sprite.zone.isInZone(this.to.x, this.to.y)) {
        let zone = this.sprite.zone.world.zoneContaining(this.to.x, this.to.y);
        if (!zone || !zone.loaded || !zone.isWalkable(this.to.x, this.to.y, Direction.reverse(facing))) {
          this.currentAction = this.sprite.faceDir(facing);
        } else {
          this.currentAction = new ActionLoader(
            this.sprite.engine,
            "changezone",
            [this.sprite.zone.id, this.sprite.pos.toArray(), zone.id, this.to.toArray(), this.length],
            this
          );
        }
      } else {
        // Load Next move
        this.currentAction = new ActionLoader(this.sprite.engine, "move", this.moveList[this.moveIndex], this.sprite);
      }
      // set facing
      this.currentAction.facing = facing;
      this.sprite.addAction(this.currentAction);
      // increment move index
      this.moveIndex = this.moveIndex + 1 >= this.moveList.length ? 0 : this.moveIndex + 1;
      this.startTime = time;
    }
    return this.completed; // loop
  },
  // Handle Keyboard
  checkInput: function (time) {
    if (time > this.lastKey + this.length) {
      switch (this.sprite.engine.keyboard.lastPressed("q")) {
        // close dialogue on q key press
        case "q":
          console.log("stopping patrol");
          this.completed = true; // toggle
        default:
          this.lastKey = new Date().getTime();
          return null;
      }
    }
  },
};
